export const adminStudentsText = {
  // 학생 관리 > 페이지와 검색·필터
  page: {
    title: "학생 관리",
    searchAriaLabel: "학생 및 학습 자료 검색",
    searchPlaceholder: "이름·학교·학년·단어장 검색",
    filterButton: "필터",
    resetFilters: "초기화",
    noMatches: "조건에 맞는 학생이 없습니다.",
  },

  // 학생 관리 > 학생 카드의 다음 범위
  recommendation: {
    complete: "현재 단어장 완료",
    manual: "DAY 범위 확인 필요",
    needsWordbook: "단어장 선택 필요",
  },

  // 학생 관리 > 학생 추가 모달 > 이름 입력 도움말
  createStudent: {
    open: "학생 추가",
    nameLabel: "학생 이름",
    nameHelp: "학생이 앱에서 확인할 이름을 입력합니다.",
    namePlaceholder: "예: 김하늘",
    schoolLabel: "학교",
    schoolPlaceholder: "예: 심석고등학교",
    gradeLabel: "학년",
    gradePlaceholder: "예: 고1",
    startingWordbookLabel: "시작 단어장",
    startingWordbookHelp:
      "처음 사용할 단어장을 지정하면 다음 시험 범위를 바로 추천할 수 있습니다.",
    chooseLater: "나중에 선택",
    memoLabel: "관리 메모",
    memoPlaceholder: "선택 사항",
    required: "필수",
    optional: "선택",
    submit: "학생과 코드 만들기",
    submitting: "만드는 중…",
    refreshing: "화면에 반영하는 중…",
    nameHelpAria: "학생 이름 도움말",
    startingWordbookHelpAria: "시작 단어장 도움말",
    noWordbookNotice: "단어장 없이 학생과 코드부터 만들 수 있습니다.",
    noCodeError: "새 접속코드를 받지 못했습니다.",
    codeTitle: "{student} 새 접속코드",
    success: "학생과 접속 코드를 만들었습니다.",
    error: "학생을 만들지 못했습니다.",
  },

  // 학생 관리 > 학생 상세 모달 > 탭
  detailTabs: {
    info: "학생 정보",
    account: "계정 설정",
    history: "내역",
  },

  // 학생 관리 > 학생 상세 > 학생 정보
  info: {
    name: "이름",
    school: "학교",
    grade: "학년",
    savePending: "저장 중…",
    save: "학생 정보 저장",
    currentWordbook: "현재 단어장",
    chooseLater: "나중에 선택",
    previousWordbook: "이전 단어장",
    assignmentClosed: "신규 배정 종료",
    saveWordbook: "단어장 저장",
    profileSuccess: "학생 정보를 저장했습니다.",
    profileError: "학생 정보를 저장하지 못했습니다.",
    wordbookSuccess: "현재 단어장을 변경했습니다.",
    wordbookError: "현재 단어장을 바꾸지 못했습니다.",
  },

  // 학생 관리 > 학생 상세 > 학습 관리
  learning: {
    nextVocabularyTitle: "다음 단어 시험",
    assign: "배정하기",
    nextVocabularyHelp:
      "최근 학습 기록과 미응시 시험을 기준으로 다음 범위를 추천합니다.",
    nextExamWrongWordHelp:
      "아직 추가 가능한 오답만 다음 단어 시험 대기에 보냅니다.",
    worksheetWrongWordHelp:
      "선택한 오답을 한 번에 50개까지 학생의 학교·학년·해석 진도와 함께 앱에 저장하고, 연결된 비공개 Google Drive의 AI 입력 파일을 직접 업데이트합니다.",
    wrongHistoryRefreshHelp:
      "첫 시험이 끝나는 즉시 오답 이력과 현재 오답 단어를 반영합니다.",
    activitySections: {
      open: "응시할 시험",
      needsAttention: "미응시 · 미통과",
      completed: "완료",
      archived: "취소 · 삭제",
    },
    activityList: {
      empty: "배정되거나 완료된 학습이 없습니다.",
      noMatches: "선택한 조건의 내역이 없습니다.",
      filterAria: "학습 내역 필터",
      filters: {
        type: "유형",
        allTypes: "전체 유형",
        regular: "단어 시험",
        mixed: "틀린 단어 포함",
        review: "오답 재시험",
        status: "상태",
        allStatuses: "전체 상태",
        open: "진행 전·진행 중",
        needsAttention: "미응시·미통과",
        completed: "통과 완료",
        archived: "취소·삭제",
        period: "기간",
        allPeriods: "전체 기간",
        recent30: "최근 30일",
        recent90: "최근 90일",
        recentYear: "최근 1년",
      },
      time: {
        deadline: "마감 {datetime}",
        assignedWithoutDeadline: "배정 {datetime} · 마감 없음",
        cancelled: "취소 {datetime}",
        missed: "미응시 마감 {datetime}",
        expired: "시간 종료 {datetime}",
        finished: "종료 {datetime}",
        failed: "미통과 {datetime}",
        started: "시작 {datetime}",
      },
      count: "{count}건",
      recentOnly: "최근 {count}개만 보기",
      showAll: "전체 {count}개 보기",
    },
    recentWordbookChange: "최근 단어장 변경",
    chooseLater: "나중에 선택",
    previousWordbook: "이전 단어장",
    assignmentClosed: "신규 배정 종료",
    save: "저장",
    recentActivity: "최근 숙제·시험",
    activityCount: "{count}개",
    backAria: "학습 관리로 돌아가기",
    vocabularyManagement: "단어 학습 관리",
    passageManagement: "지문 학습 관리",
    nextVocabularyHelpAria: "다음 단어 시험 도움말",
    passagePending:
      "교과서·부교재·모의고사 범위 계약이 확정되면 이곳에서 지문 학습을 배정합니다.",
    source: {
      fallbackPrimary: "미선택",
      openAria: "{type} 학습 관리 열기",
    },
    wordbookHistory: {
      inProgress: "진행 중",
      expired: "시간 종료",
      passed: "통과",
      failed: "미통과",
      title: "학습한 단어장",
      count: "{count}개",
      empty: "아직 실제로 응시한 단어장이 없습니다.",
      recent: "최근 단어장",
      lastRange: "마지막 범위",
      recentStudy: "최근 학습",
      attempts: "응시",
      attemptCount: "{count}회",
    },
    wrongWordsPanel: {
      retryRecovered: "재시험에서 정답",
      retryWrong: "재시험에서도 오답",
      retryUnanswered: "재시험 미응답",
      loadError: "오답 단어를 불러오지 못했습니다.",
      queueError: "오답 단어를 다음 시험 대기열에 추가하지 못했습니다.",
      queueSuccess: "{count}개 단어를 다음 시험 대기열에 추가했습니다.",
      worksheetError: "해석 시험지 요청을 저장하지 못했습니다.",
      worksheetDriveNotConfigured:
        "범위는 앱에 저장했습니다. Google Drive 연결 후 같은 버튼을 다시 눌러 동기화해 주세요.",
      worksheetDriveFailed:
        "범위는 앱에 저장했지만 Google Drive 업데이트에 실패했습니다. 다시 시도해 주세요.",
      worksheetUnchanged: "이미 같은 해석 시험지 범위가 동기화되어 있습니다.",
      worksheetDuplicate:
        "{count}개 단어의 같은 요청이 이미 저장되어 있습니다.",
      worksheetSuccess: "{count}개 단어의 해석 시험지 범위를 Drive에 업데이트했습니다.",
      cancelDraftError: "재시험 준비를 취소하지 못했습니다.",
      cancelDraftSuccess:
        "재시험 준비를 취소했습니다. 오답은 다음 단어 시험 대기에 남아 있습니다.",
      loading: "오답 단어를 불러오는 중…",
      retryLoad: "다시 불러오기",
      openToLoad: "오답 탭을 열면 이력을 불러옵니다.",
      refreshing: "최신 오답 이력을 확인하는 중…",
      refreshBasis: "오답 반영 기준",
      refreshBasisHelpAria: "오답 반영 기준 도움말",
      refresh: "새로고침",
      summary: {
        event: "누적 오답",
        current: "현재 오답 단어",
        once: "누적 1회",
        repeated: "누적 2회 이상",
        pending: "다음 시험 대기",
        times: "{count}회",
        count: "{count}개",
      },
      legacyDraftNotice:
        "이전 방식으로 준비 중인 재시험이 있습니다. 취소하면 단어는 다음 단어 시험 대기에 그대로 남습니다.",
      draftSummary: "{dataset} · {count}개",
      wordbookFallback: "단어장",
      canceling: "취소하는 중…",
      cancelDraft: "재시험 준비 취소",
      search: "단어 검색",
      searchPlaceholder: "영어·뜻·단어장",
      wordbook: "단어장",
      allWordbooks: "전체 단어장",
      levelFilterAria: "오답 횟수 필터",
      all: "전체",
      once: "누적 1회",
      repeated: "누적 2회 이상",
      purposeAria: "오답 단어 작업",
      nextExam: "다음 시험",
      worksheet: "해석 시험지 범위",
      purposeHelpAria: "오답 단어 작업 도움말",
      clearVisible: "보이는 선택 해제",
      selectVisible: "보이는 단어 선택",
      selectedCount: "{count}개 선택",
      worksheetPending: "담는 중…",
      addToWorksheet: "해석 시험지 범위 업데이트",
      readingCurriculum: "배운 해석 범위",
      readingContextStatus: {
        not_synced: "업데이트 전",
        not_configured: "Drive 연결 필요",
        synced: "Drive 업데이트됨",
        failed: "Drive 업데이트 실패",
      },
      queuePending: "추가하는 중…",
      addToNextExam: "다음 시험에 추가",
      downloadJson: "익명 기준본 JSON 받기",
      empty: "조건에 맞는 오답 단어가 없습니다.",
      wordAria: "{word}을(를) {action}",
      resolved: "해결됨",
      assigned: "배정 중",
      pending: "다음 시험 대기",
      available: "추가 가능",
      wrongCount: "누적 {count}회",
    },
  },

  // 학생 관리 > 학생 목록 카드
  card: {
    wordbookMissing: "단어장 미선택",
    active: "접속 가능",
    blocked: "차단됨",
    codeExpired: "코드 만료됨",
    schoolMissing: "학교 미입력",
    gradeMissing: "학년 미입력",
    recentWordbook: "최근 단어장",
    learningMaterials: "학습 자료",
    nextRange: "다음 범위",
    priority: "우선 확인",
    noHistory: "학습 기록 없음",
  },

  // 학생 관리 > 학생 상세 모달 > 공통 헤더
  detail: {
    missingSchoolGrade: "학교·학년 미입력",
    tabsAria: "학생 상세 메뉴",
  },

  // 학생 관리 > 학생 상세 모달 > 계정 설정
  account: {
    status: "계정 상태",
    active: "접속 가능",
    blocked: "차단됨",
    expiredNotice:
      "기존 접속 코드가 만료되었습니다. 코드 교체 후 새 코드를 전달해 주세요.",
    viewCode: "코드 보기",
    rotateCode: "코드 교체",
    block: "접속 차단",
    resume: "새 코드로 재개",
    deletePending: "학생 삭제 중…",
    delete: "학생 삭제",
    rotateConfirm:
      "{student} 학생의 기존 접속을 모두 끊고 새 코드를 발급할까요?",
    rotateSuccess: "접속 코드를 교체했습니다.",
    rotateError: "접속코드를 바꾸지 못했습니다.",
    blockConfirm: "{student} 학생의 코드와 현재 접속을 바로 차단할까요?",
    blockSuccess: "학생 접속을 차단했습니다.",
    blockError: "접속을 차단하지 못했습니다.",
    deleteConfirm:
      "{student} 학생을 삭제할까요? 학생의 접속은 즉시 차단되고 목록에서는 사라집니다. 진행 중인 시험은 종료 처리하며 기존 시험·성적은 보존되어 내역에는 '삭제됨'으로 표시됩니다.",
    deleteSuccess: "학생을 삭제했습니다. 기존 내역은 삭제됨으로 보존됩니다.",
    deleteError: "학생을 삭제하지 못했습니다.",
  },

  // 학생 관리 > 학생 코드 모달
  codeModal: {
    sendKakao: "카카오톡으로 보내기",
    copy: "코드 복사",
    copied: "복사됨",
    close: "닫기",
    copySuccess: "학생 코드를 복사했습니다.",
    copyFailure: "학생 코드를 복사하지 못했습니다.",
    kakaoOpened: "카카오톡 공유 창을 열었습니다.",
    kakaoFallbackUnconfigured: "카카오 설정 전이라 메시지를 복사했습니다.",
    kakaoFallbackFailed: "카카오톡을 열지 못해 메시지를 복사했습니다.",
    kakaoFallbackCopyFailure:
      "카카오톡을 열거나 공유 메시지를 복사하지 못했습니다.",
    genericRequestError: "요청을 처리하지 못했습니다.",
    missingCodeError: "접속코드를 받지 못했습니다.",
    revealTitle: "{student} 접속코드",
    revealError: "접속코드를 불러오지 못했습니다.",
    rotateTitle: "{student} 새 접속코드",
    addressLine: "접속 주소: {url}",
    codeLine: "접속 코드: {code}",
  },
} as const;
